/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Idea = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isFavorite' : IDL.Bool,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'createIdea' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Idea], []),
  'deleteIdea' : IDL.Func([IDL.Nat], [], []),
  'getAllIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
  'toggleFavorite' : IDL.Func([IDL.Nat], [Idea], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Idea = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isFavorite' : IDL.Bool,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'createIdea' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Idea], []),
    'deleteIdea' : IDL.Func([IDL.Nat], [], []),
    'getAllIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
    'toggleFavorite' : IDL.Func([IDL.Nat], [Idea], []),
  });
};

export const init = ({ IDL }) => { return []; };